In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('User_Data.csv')

In [3]:
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [7]:
x=df.iloc[:,[2,3]].values
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [8]:
y=df.iloc[:,4].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [36]:
from sklearn.model_selection import train_test_split
x_train,y_train,x_test,y_test=train_test_split(x,y,test_size=0.25,random_state=0)


In [37]:
from sklearn.preprocessing import StandardScaler

In [38]:
sc=StandardScaler()
sc

StandardScaler()

In [39]:
x_train=sc.fit_transform(x_train)

In [45]:
from sklearn.naive_bayes import GaussianNB

In [46]:
classifier=GaussianNB()

In [48]:
x_train = x_train[:200]
y_train = y_train.ravel()

# Fit the classifier
classifier.fit(x_train, y_train)


GaussianNB()

In [53]:
from sklearn.preprocessing import StandardScaler

# Ensure sc is properly defined and fitted
sc = StandardScaler()
sc.fit(x_train)  # x_train should be your training data

# Now transform x_test
x_test = sc.transform(x_test)  # Apply the scaler to x_test
print("x_test shape after scaling:", x_test.shape)

# Predict
y_pred = classifier.predict(x_test)


TypeError: float() argument must be a string or a real number, not 'StandardScaler'

In [35]:
y_pred

array([   35,    35, 60000, 60000,    35, 60000, 60000, 60000,    35,
       60000, 60000, 60000,    35, 60000,    35,    35,    35,    35,
          35, 60000, 60000, 60000, 60000, 60000, 60000,    35, 60000,
       60000, 60000, 60000, 60000, 60000, 60000,    35, 60000,    35,
          35,    35, 60000,    35, 60000,    35, 60000,    35, 60000,
          35, 60000, 60000,    35, 60000, 60000,    35, 60000,    35,
       60000,    35, 60000, 60000, 60000,    35, 60000, 60000,    35,
       60000, 60000, 60000,    35, 60000, 60000, 60000, 60000, 60000,
       60000,    35,    35,    35,    35, 60000, 60000, 60000, 60000,
          35, 60000, 60000, 60000, 60000, 60000,    35,    35,    35,
       60000, 60000, 60000,    35, 60000,    35,    35,    35, 60000,
          35, 60000, 60000,    35, 60000, 60000,    35,    35, 60000,
          35, 60000, 60000,    35, 60000, 60000, 60000,    35, 60000,
          35, 60000, 60000, 60000, 60000, 60000, 60000,    35, 60000,
          35, 60000,

In [52]:
#confusion Matrix cm

In [ ]:
import seaborn as sns
sns.heatmap(pd.DataFrame(cm),annot=True)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy=accuracy_score(y_test,y_pred)