# numpy basic

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
n = np.array([1,2,3,4])
n

array([1, 2, 3, 4])

In [5]:
li = [1,2,3]
li*2

[1, 2, 3, 1, 2, 3]

In [6]:
a=np.array([1,2,3])
print(a*2)
print(a+2)
print(a-2)
print(a/2)
print(a**2)
print(a%2)
print(a**4)

[2 4 6]
[3 4 5]
[-1  0  1]
[0.5 1.  1.5]
[1 4 9]
[1 0 1]
[ 1 16 81]


In [7]:
d=np.array([[1,2,3],[1,2,3]])
d

array([[1, 2, 3],
       [1, 2, 3]])

In [8]:
d.shape

(2, 3)

In [9]:
d.size

6

In [10]:
d.dtype

dtype('int64')

In [11]:
a=np.array([[1,2,3],[1,2,3]])
b=a.reshape(3,2)
b

array([[1, 2],
       [3, 1],
       [2, 3]])

In [12]:
x=[1,2,3]
print(x)
a=np.asarray(x)
a

[1, 2, 3]


array([1, 2, 3])

In [13]:
x=np.arange(11)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
a=x[2:7:2]
a

array([2, 4, 6])

In [15]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
a=x[1,1:2]
a

array([5])

In [17]:
a=x[1,1:]
a

array([5, 6])

In [18]:
x.dtype

dtype('int64')

In [19]:
x.dtype=float

In [20]:
x

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323],
       [3.5e-323, 4.0e-323, 4.4e-323]])

In [21]:
x.dtype

dtype('float64')

In [22]:
x.dtype=int

In [23]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
x.dtype

dtype('int64')

In [28]:
y=np.array([[1,2,3,4],[5,5,6,7],[8,9,5,2]])
y

array([[1, 2, 3, 4],
       [5, 5, 6, 7],
       [8, 9, 5, 2]])

In [29]:
y.ndim

2

In [30]:
x=y.reshape(4,3)
x

array([[1, 2, 3],
       [4, 5, 5],
       [6, 7, 8],
       [9, 5, 2]])

In [32]:
a=x.reshape(6,2)
a

array([[1, 2],
       [3, 4],
       [5, 5],
       [6, 7],
       [8, 9],
       [5, 2]])

In [33]:
b=a.reshape(1,12)
b

array([[1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 5, 2]])

In [35]:
a=b.reshape(12,1)
a

array([[1],
       [2],
       [3],
       [4],
       [5],
       [5],
       [6],
       [7],
       [8],
       [9],
       [5],
       [2]])

In [37]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1+arr2)
print(np.add(arr1,arr2))
print(np.power(arr1,arr2))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[    1    64]
 [ 2187 65536]]


In [39]:
print(np.concatenate([arr1,arr2]))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [40]:
print(np.hstack([arr1,arr2]))

[[1 2 5 6]
 [3 4 7 8]]


In [42]:
print(np.vstack([arr1,arr2]))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [44]:
arr=np.array([1,2,3])
print(np.append(arr,[40,50]))

[ 1  2  3 40 50]


In [47]:
print(np.delete(arr,0,axis=0))

[2 3]


In [50]:
print(np.insert(arr,3,[4],axis=0))

[1 2 3 4]


In [52]:
y=np.array([[1,2,3,4],[5,5,6,7],[8,9,5,2]])
print(np.delete(y,2,axis=1))

[[1 2 4]
 [5 5 7]
 [8 9 2]]
