# numpy basic

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [4]:
n = np.array([1,2,3,4])
n

array([1, 2, 3, 4])

In [5]:
li = [1,2,3]
li*2

[1, 2, 3, 1, 2, 3]

In [36]:
a=np.array([1,2,3])
print(a*2)
print(a+2)
print(a-2)
print(a/2)
print(a**2)
print(a%2)
print(a**4)

[2 4 6]
[3 4 5]
[-1  0  1]
[0.5 1.  1.5]
[1 4 9]
[1 0 1]
[ 1 16 81]


In [25]:
d=np.array([[1,2,3],[1,2,3]])
d

array([[1, 2, 3],
       [1, 2, 3]])

In [26]:
d.shape

(2, 3)

In [27]:
d.size

6

In [28]:
d.dtype

dtype('int64')

In [29]:
a=np.array([[1,2,3],[1,2,3]])
b=a.reshape(3,2)
b

array([[1, 2],
       [3, 1],
       [2, 3]])

In [30]:
x=[1,2,3]
print(x)
a=np.asarray(x)
a

[1, 2, 3]


array([1, 2, 3])

In [31]:
x=np.arange(11)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
a=x[2:7:2]
a

array([2, 4, 6])

In [33]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
a=x[1,1:2]
a

array([5])

In [35]:
a=x[1,1:]
a

array([5, 6])